import {
  pgTable,
  pgEnum,
  uuid,
  text,
  integer,
  boolean,
  timestamp,
  jsonb,
  unique,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import type { SeoOverrides } from "@/lib/seo";

// ──────────────────────────────────────────────
// Enums
// ──────────────────────────────────────────────

export const orderStatusEnum = pgEnum("order_status", [
  "pending",
  "completed",
  "failed",
  "refunded",
]);

export const paymentMethodEnum = pgEnum("payment_method", [
  "bkash",
  "nagad",
  "rocket",
  "bank_transfer",
  "ssl_commerz",
]);

export const licenseStatusEnum = pgEnum("license_status", [
  "active",
  "expired",
  "revoked",
  "suspended",
  "grace_period",
]);

export const ticketStatusEnum = pgEnum("ticket_status", [
  "open",
  "in_progress",
  "resolved",
  "closed",
]);

export const ticketPriorityEnum = pgEnum("ticket_priority", [
  "low",
  "medium",
  "high",
  "urgent",
]);

export const couponTypeEnum = pgEnum("coupon_type", [
  "percentage",
  "flat",
]);

export const redirectTypeEnum = pgEnum("redirect_type", ["301", "302"]);

export const redirectStatusEnum = pgEnum("redirect_status", [
  "active",
  "inactive",
]);

export const versionStatusEnum = pgEnum("version_status", [
  "stable",
  "beta",
  "draft",
]);

export const licenseTypeEnum = pgEnum("license_type", [
  "lifetime",
  "subscription",
]);

export const billingCycleEnum = pgEnum("billing_cycle", [
  "monthly",
  "yearly",
  "custom",
]);

export const activationActionEnum = pgEnum("activation_action", [
  "activate",
  "deactivate",
]);

export const verificationMethodEnum = pgEnum("verification_method", [
  "dns",
  "file",
  "meta",
]);

// ──────────────────────────────────────────────
// Auth Tables (generated by Better Auth CLI)
// ──────────────────────────────────────────────

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  role: text("role").default("customer"),
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
  twoFactorEnabled: boolean("two_factor_enabled").default(false),
  phone: text("phone").notNull(),
  centralUserId: text("central_user_id"),
});

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const twoFactor = pgTable(
  "two_factor",
  {
    id: text("id").primaryKey(),
    secret: text("secret").notNull(),
    backupCodes: text("backup_codes").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    verified: boolean("verified").default(true),
  },
  (table) => [
    index("twoFactor_secret_idx").on(table.secret),
    index("twoFactor_userId_idx").on(table.userId),
  ],
);

// ──────────────────────────────────────────────
// Application Tables
// ──────────────────────────────────────────────

export const orders = pgTable("orders", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: text("user_id").notNull(),
  centralOrderId: text("central_order_id"),
  productId: text("product_id").notNull(),
  plan: text("plan").notNull(),
  amount: integer("amount").notNull(),
  currency: text("currency").notNull().default("BDT"),
  paymentMethod: paymentMethodEnum("payment_method"),
  paymentRef: text("payment_ref"),
  status: orderStatusEnum("status").notNull().default("pending"),
  couponCode: text("coupon_code"),
  discountAmount: integer("discount_amount").default(0),
  taxAmount: integer("tax_amount").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const licenses = pgTable(
  "licenses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: text("user_id").notNull(),
    centralLicenseId: text("central_license_id"),
    orderId: uuid("order_id").references(() => orders.id),
    productId: text("product_id").notNull(),
    plan: text("plan").notNull(),
    licenseKey: text("license_key").notNull(),
    status: licenseStatusEnum("status").notNull().default("active"),
    activationDomains: jsonb("activation_domains").default([]),
    maxActivations: integer("max_activations").default(1),
    currentActivations: integer("current_activations").default(0),
    apiTokenHash: text("api_token_hash"),
    expiresAt: timestamp("expires_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [unique("licenses_license_key_unique").on(t.licenseKey)],
);

export const licenseActivations = pgTable(
  "license_activations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    licenseId: uuid("license_id")
      .notNull()
      .references(() => licenses.id, { onDelete: "cascade" }),
    domain: text("domain").notNull(),
    action: activationActionEnum("action").notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    verificationMethod: verificationMethodEnum("verification_method"),
    suspiciousFlags: jsonb("suspicious_flags").$type<string[]>().default([]),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => [
    index("license_activations_license_id_idx").on(table.licenseId),
    index("license_activations_created_at_idx").on(table.createdAt),
    index("license_activations_domain_idx").on(table.domain),
  ]
);

export const licenseReminders = pgTable(
  "license_reminders",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    licenseId: uuid("license_id")
      .notNull()
      .references(() => licenses.id, { onDelete: "cascade" }),
    milestone: text("milestone").notNull(),
    sentAt: timestamp("sent_at").notNull().defaultNow(),
  },
  (table) => [
    unique("license_reminders_license_id_milestone_unique").on(
      table.licenseId,
      table.milestone
    ),
    index("license_reminders_license_id_idx").on(table.licenseId),
  ]
);

export const downloads = pgTable("downloads", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: text("user_id").notNull(),
  productId: text("product_id").notNull(),
  version: text("version").notNull(),
  fileName: text("file_name").notNull(),
  downloadToken: text("download_token").notNull().unique(),
  expiresAt: timestamp("expires_at").notNull(),
  downloadedAt: timestamp("downloaded_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const tickets = pgTable("tickets", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: text("user_id").notNull(),
  subject: text("subject").notNull(),
  description: text("description").notNull(),
  status: ticketStatusEnum("status").notNull().default("open"),
  priority: ticketPriorityEnum("priority").notNull().default("medium"),
  assignedTo: text("assigned_to"),
  attachments: jsonb("attachments").default([]),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const ticketMessages = pgTable("ticket_messages", {
  id: uuid("id").defaultRandom().primaryKey(),
  ticketId: uuid("ticket_id")
    .notNull()
    .references(() => tickets.id),
  userId: text("user_id").notNull(),
  message: text("message").notNull(),
  attachments: jsonb("attachments").default([]),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const notifications = pgTable("notifications", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: text("user_id").notNull(),
  type: text("type").notNull(),
  title: text("title").notNull(),
  message: text("message").notNull(),
  data: jsonb("data"),
  read: boolean("read").default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const auditLogs = pgTable("audit_logs", {
  id: uuid("id").defaultRandom().primaryKey(),
  actorId: text("actor_id"),
  actorRole: text("actor_role"),
  action: text("action").notNull(),
  targetType: text("target_type"),
  targetId: text("target_id"),
  details: jsonb("details"),
  ipAddress: text("ip_address"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const coupons = pgTable("coupons", {
  id: uuid("id").defaultRandom().primaryKey(),
  code: text("code").notNull().unique(),
  type: couponTypeEnum("type").notNull(),
  value: integer("value").notNull(),
  minOrderAmount: integer("min_order_amount").default(0),
  maxUses: integer("max_uses"),
  currentUses: integer("current_uses").default(0),
  expiresAt: timestamp("expires_at"),
  active: boolean("active").default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const paymentAccounts = pgTable("payment_accounts", {
  id: uuid("id").defaultRandom().primaryKey(),
  method: paymentMethodEnum("method").notNull(),
  accountName: text("account_name").notNull(),
  accountNumber: text("account_number").notNull(),
  bankName: text("bank_name"),
  branch: text("branch"),
  routingNumber: text("routing_number"),
  instructions: text("instructions"),
  active: boolean("active").default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const settings = pgTable("settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// ──────────────────────────────────────────────
// Webhook Tables
// ──────────────────────────────────────────────

export const webhookStatusEnum = pgEnum("webhook_status", [
  "active",
  "inactive",
]);

export const webhooks = pgTable("webhooks", {
  id: uuid("id").defaultRandom().primaryKey(),
  url: text("url").notNull(),
  events: jsonb("events").$type<string[]>().notNull(),
  secret: text("secret").notNull(),
  status: webhookStatusEnum("status").notNull().default("active"),
  lastTriggeredAt: timestamp("last_triggered_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const webhookDeliveries = pgTable("webhook_deliveries", {
  id: uuid("id").defaultRandom().primaryKey(),
  webhookId: uuid("webhook_id")
    .notNull()
    .references(() => webhooks.id, { onDelete: "cascade" }),
  event: text("event").notNull(),
  payload: jsonb("payload"),
  statusCode: integer("status_code"),
  response: text("response"),
  success: boolean("success").default(false),
  attempts: integer("attempts").default(1),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ──────────────────────────────────────────────
// Products Tables (D-01 through D-07)
// ──────────────────────────────────────────────

export const products = pgTable("products", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  description: text("description"),
  currentVersion: text("current_version"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const productVersions = pgTable(
  "product_versions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    version: text("version").notNull(),
    downloadUrl: text("download_url"),
    changelog: text("changelog"),
    status: versionStatusEnum("status").notNull().default("draft"),
    releasedAt: timestamp("released_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    unique("product_versions_product_id_version_unique").on(
      table.productId,
      table.version
    ),
  ]
);

export const productPlans = pgTable(
  "product_plans",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    description: text("description"),
    priceBDT: integer("price_bdt").notNull().default(0),
    priceUSD: integer("price_usd").notNull().default(0),
    licenseType: licenseTypeEnum("license_type").notNull().default("subscription"),
    billingCycle: billingCycleEnum("billing_cycle"),
    billingDurationMonths: integer("billing_duration_months"),
    maxActivations: integer("max_activations").default(1),
    features: jsonb("features").$type<Record<string, boolean>>().default({}),
    sortOrder: integer("sort_order").default(0),
    active: boolean("active").default(true),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    unique("product_plans_product_id_slug_unique").on(
      table.productId,
      table.slug
    ),
  ]
);

export const redirects = pgTable(
  "redirects",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    fromUrl: text("from_url").notNull(),
    toUrl: text("to_url").notNull(),
    type: redirectTypeEnum("type").notNull().default("301"),
    isRegex: boolean("is_regex").default(false).notNull(),
    hitCount: integer("hit_count").default(0).notNull(),
    status: redirectStatusEnum("status").notNull().default("active"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("redirects_from_url_idx").on(table.fromUrl),
    index("redirects_status_idx").on(table.status),
  ]
);

export const seo404Errors = pgTable(
  "seo_404_errors",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    url: text("url").notNull(),
    referrer: text("referrer"),
    hitCount: integer("hit_count").default(1).notNull(),
    lastSeenAt: timestamp("last_seen_at").notNull().defaultNow(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => [
    unique("seo_404_errors_url_unique").on(table.url),
    index("seo_404_errors_last_seen_idx").on(table.lastSeenAt),
  ]
);

// ──────────────────────────────────────────────
// Blog Tables
// ──────────────────────────────────────────────

export const blogPostStatusEnum = pgEnum("blog_post_status", [
  "draft",
  "published",
]);

export const blogCategories = pgTable(
  "blog_categories",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    locale: text("locale").notNull(),
    description: text("description"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("blog_categories_locale_idx").on(table.locale),
    unique("blog_categories_slug_locale_unique").on(table.slug, table.locale),
  ]
);

export const blogPosts = pgTable(
  "blog_posts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    title: text("title").notNull(),
    slug: text("slug").notNull(),
    content: text("content").notNull(),
    excerpt: text("excerpt"),
    coverImage: text("cover_image"),
    authorName: text("author_name").notNull(),
    locale: text("locale").notNull(),
    status: blogPostStatusEnum("status").notNull().default("draft"),
    categoryId: uuid("category_id").references(() => blogCategories.id),
    tags: jsonb("tags").$type<string[]>().default([]),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    ogImage: text("og_image"),
    seoOverrides: jsonb("seo_overrides").$type<SeoOverrides>(),
    publishedAt: timestamp("published_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("blog_posts_locale_idx").on(table.locale),
    index("blog_posts_status_idx").on(table.status),
    unique("blog_posts_slug_locale_unique").on(table.slug, table.locale),
  ]
);

// ──────────────────────────────────────────────
// Event Bus Tables
// ──────────────────────────────────────────────

/**
 * Events table for event persistence (D-14, D-18, D-19)
 *
 * Stores all domain events for replay, debugging, analytics, and state rebuilding.
 * Single table for all event types with key fields as columns and full payload in JSONB.
 *
 * Schema design (D-19: hybrid columns):
 * - Key fields (id, type, aggregate_id, timestamp) as columns for queryability
 * - Full payload in JSONB for flexibility
 * - Indexes on type, aggregateId, timestamp for common queries
 * - Single table for all event types (D-18)
 */
export const events = pgTable(
  "events",
  {
    id: text("id").primaryKey(),
    type: text("type").notNull(),
    aggregateId: text("aggregate_id").notNull(),
    payload: jsonb("payload").notNull(),
    timestamp: timestamp("timestamp").defaultNow().notNull(),
    correlationId: text("correlation_id"),
    metadata: jsonb("metadata"),
  },
  (table) => ({
    typeIdx: index("events_type_idx").on(table.type),
    aggregateIdx: index("events_aggregate_id_idx").on(table.aggregateId),
    timestampIdx: index("events_timestamp_idx").on(table.timestamp),
    correlationIdx: index("events_correlation_id_idx").on(table.correlationId),
  })
);

// ──────────────────────────────────────────────
// Relations
// ──────────────────────────────────────────────

// Auth relations
export const userRelations = relations(user, ({ many }) => ({
  accounts: many(account),
  twoFactors: many(twoFactor),
  orders: many(orders),
  licenses: many(licenses),
  downloads: many(downloads),
  tickets: many(tickets),
  notifications: many(notifications),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

export const twoFactorRelations = relations(twoFactor, ({ one }) => ({
  user: one(user, {
    fields: [twoFactor.userId],
    references: [user.id],
  }),
}));

// Application relations
export const ordersRelations = relations(orders, ({ one }) => ({
  user: one(user, {
    fields: [orders.userId],
    references: [user.id],
  }),
}));

export const licensesRelations = relations(licenses, ({ one, many }) => ({
  order: one(orders, {
    fields: [licenses.orderId],
    references: [orders.id],
  }),
  user: one(user, {
    fields: [licenses.userId],
    references: [user.id],
  }),
  activations: many(licenseActivations),
  reminders: many(licenseReminders),
}));

export const licenseActivationsRelations = relations(licenseActivations, ({ one }) => ({
  license: one(licenses, {
    fields: [licenseActivations.licenseId],
    references: [licenses.id],
  }),
}));

export const licenseRemindersRelations = relations(licenseReminders, ({ one }) => ({
  license: one(licenses, {
    fields: [licenseReminders.licenseId],
    references: [licenses.id],
  }),
}));

export const downloadsRelations = relations(downloads, ({ one }) => ({
  user: one(user, {
    fields: [downloads.userId],
    references: [user.id],
  }),
}));

export const ticketsRelations = relations(tickets, ({ one, many }) => ({
  user: one(user, {
    fields: [tickets.userId],
    references: [user.id],
  }),
  messages: many(ticketMessages),
}));

export const ticketMessagesRelations = relations(ticketMessages, ({ one }) => ({
  ticket: one(tickets, {
    fields: [ticketMessages.ticketId],
    references: [tickets.id],
  }),
}));

export const notificationsRelations = relations(notifications, ({ one }) => ({
  user: one(user, {
    fields: [notifications.userId],
    references: [user.id],
  }),
}));

export const webhooksRelations = relations(webhooks, ({ many }) => ({
  deliveries: many(webhookDeliveries),
}));

export const webhookDeliveriesRelations = relations(webhookDeliveries, ({ one }) => ({
  webhook: one(webhooks, {
    fields: [webhookDeliveries.webhookId],
    references: [webhooks.id],
  }),
}));

// Products relations
export const productsRelations = relations(products, ({ many }) => ({
  versions: many(productVersions),
  plans: many(productPlans),
}));

export const productVersionsRelations = relations(productVersions, ({ one }) => ({
  product: one(products, {
    fields: [productVersions.productId],
    references: [products.id],
  }),
}));

export const productPlansRelations = relations(productPlans, ({ one }) => ({
  product: one(products, {
    fields: [productPlans.productId],
    references: [products.id],
  }),
}));
