// Base repository implementation for DDD infrastructure
// Follows D-20, D-21, D-23 from Phase 14 CONTEXT.md

import { eq, and, asc, desc, sql } from 'drizzle-orm';
import type { SQL } from 'drizzle-orm';
import { db } from '@/lib/db';
import type { IRepository, QueryBuilder, IMapper } from './types';

/**
 * Base repository class providing CRUD operations and query builder
 * All bounded context repositories extend this class (D-20, D-22)
 *
 * Implements domain-to-data mapping via IMapper (D-23)
 * Uses Drizzle ORM native transactions (D-21)
 *
 * @template T - Domain entity type (not DB row type)
 * @template Data - Database row type (Drizzle schema type)
 */
export class BaseRepository<T, Data> implements IRepository<T> {
  /**
   * Protected database client from @/lib/db
   * Subclasses use this for all database operations
   */
  protected readonly db = db;

  /**
   * Protected Drizzle table schema reference
   * Subclasses provide their specific table in constructor
   */
  protected readonly table: any;

  /**
   * Protected mapper for domain-to-data conversion (D-23)
   * Converts between DB rows and domain entities
   */
  protected readonly mapper: IMapper<T, Data>;

  /**
   * Create a new BaseRepository instance
   * @param table - Drizzle table schema reference (e.g., licenses, orders)
   * @param mapper - Mapper implementation for domain-to-data conversion
   */
  constructor(table: any, mapper: IMapper<T, Data>) {
    this.table = table;
    this.mapper = mapper;
  }

  /**
   * Find a single entity by its ID
   * Uses Drizzle eq() for equality comparison
   * @param id - Entity identifier
   * @returns Entity if found, null otherwise
   */
  async findById(id: string): Promise<T | null> {
    const result = await this.db
      .select()
      .from(this.table)
      .where(eq(this.table.id, id))
      .limit(1);

    if (result.length === 0) {
      return null;
    }

    return this.mapper.toDomain(result[0] as Data);
  }

  /**
   * Find all entities matching optional filters
   * Builds query with where, orderBy, limit, offset support (D-20)
   * @param filters - Query builder options (where, orderBy, limit, offset)
   * @returns Array of entities (empty if none match)
   */
  async findAll(filters?: QueryBuilder): Promise<T[]> {
    let query = this.db.select().from(this.table);

    // Apply WHERE clause if provided
    if (filters?.where) {
      const whereClause = Array.isArray(filters.where)
        ? and(...filters.where)
        : filters.where;
      if (whereClause) {
        query = (query as any).where(whereClause);
      }
    }

    // Apply ORDER BY if provided
    if (filters?.orderBy) {
      const orderDirection =
        filters.orderBy.direction === 'asc' ? asc : desc;
      // @ts-ignore - dynamic column access
      query = (query as any).orderBy(orderDirection(this.table[filters.orderBy.column]));
    }

    // Apply LIMIT if provided
    if (filters?.limit !== undefined) {
      query = (query as any).limit(filters.limit);
    }

    // Apply OFFSET if provided
    if (filters?.offset !== undefined) {
      query = (query as any).offset(filters.offset);
    }

    const results = await query;

    // Map all DB rows to domain entities
    return results.map((row) => this.mapper.toDomain(row as Data));
  }

  /**
   * Create a new entity
   * Converts domain entity to DB data via mapper (D-23)
   * @param data - Entity data without id (id is generated by DB)
   * @returns Created entity with generated id
   */
  async create(data: Omit<T, 'id'>): Promise<T> {
    // Convert domain entity to DB data
    const dbData = this.mapper.toData(data as T);

    // Insert and return the created record
    const result = await this.db
      .insert(this.table)
      .values(dbData as any)
      .returning();

    // Convert DB row back to domain entity
    return this.mapper.toDomain(result[0] as Data);
  }

  /**
   * Update an existing entity
   * Uses Drizzle eq() for ID comparison
   * @param id - Entity identifier
   * @param data - Partial entity data to update
   * @returns Updated entity
   */
  async update(id: string, data: Partial<T>): Promise<T> {
    // Convert partial domain data to DB data
    const dbData = this.mapper.toData(data as T);

    // Update and return the updated record
    const result = await this.db
      .update(this.table)
      .set(dbData as any)
      .where(eq(this.table.id, id))
      .returning();

    if (result.length === 0) {
      throw new Error(`Entity with id ${id} not found`);
    }

    return this.mapper.toDomain(result[0] as Data);
  }

  /**
   * Delete an entity by ID
   * Uses Drizzle eq() for ID comparison
   * @param id - Entity identifier
   */
  async delete(id: string): Promise<void> {
    await this.db.delete(this.table).where(eq(this.table.id, id));
  }

  /**
   * Check if an entity exists by ID
   * Uses COUNT query for efficiency
   * @param id - Entity identifier
   * @returns true if entity exists, false otherwise
   */
  async exists(id: string): Promise<boolean> {
    const result = await this.db
      .select({ count: sql<number>`count(*)::int` })
      .from(this.table)
      .where(eq(this.table.id, id))
      .limit(1);

    return (result[0]?.count ?? 0) > 0;
  }

  /**
   * Execute operations within a database transaction
   * Uses Drizzle native db.transaction() (D-21)
   * @template R - Return type of the transaction callback
   * @param callback - Transaction callback receiving transaction DB instance
   * @returns Result of the transaction callback
   */
  async transaction<R>(
    callback: (trx: typeof db) => Promise<R>
  ): Promise<R> {
    return (this.db as any).transaction(callback);
  }
}

export default BaseRepository;
