/**
 * ProductMapper - Domain-to-data mapper for Product entity
 *
 * Converts between Product domain entities and products table rows.
 * Implements IMapper from Phase 14 shared infrastructure (D-23).
 */

import type { IMapper } from "@/shared/infrastructure/repositories";
import { Product } from "@/modules/products/domain/entities/Product";
import type { products } from "@/lib/db/schema";

export class ProductMapper implements IMapper<Product, typeof products.$inferSelect> {
  /**
   * Convert database row to Product domain entity.
   */
  toDomain(row: typeof products.$inferSelect): Product {
    return new Product(
      row.id,
      row.name,
      row.slug,
      row.description,
      row.currentVersion,
      row.createdAt,
      row.updatedAt,
    );
  }

  /**
   * Convert Product domain entity to database row data.
   * Omits id (generated by DB) and timestamps (handled by DB defaults).
   */
  toData(domain: Product): typeof products.$inferInsert {
    return {
      id: domain.id,
      name: domain.name,
      slug: domain.slug,
      description: domain.description,
      currentVersion: domain.currentVersion,
    };
  }
}
