/**
 * ProductPlanMapper - Domain-to-data mapper for ProductPlan entity
 *
 * Converts between ProductPlan domain entities and productPlans table rows.
 * Implements IMapper from Phase 14 shared infrastructure (D-23).
 */

import type { IMapper } from "@/shared/infrastructure/repositories";
import { ProductPlan } from "@/modules/products/domain/entities/ProductPlan";
import type { productPlans } from "@/lib/db/schema";

export class ProductPlanMapper implements IMapper<ProductPlan, typeof productPlans.$inferInsert> {
  /**
   * Convert database row to ProductPlan domain entity.
   */
  toDomain(row: typeof productPlans.$inferSelect): ProductPlan {
    return new ProductPlan(
      row.id,
      row.productId,
      row.name,
      row.slug,
      row.description,
      row.priceBDT,
      row.priceUSD,
      row.licenseType,
      row.billingCycle,
      row.billingDurationMonths,
      row.maxActivations ?? 1,
      (row.features as Record<string, Record<string, boolean>>) ?? {},
      row.sortOrder ?? 0,
      row.active ?? true,
      row.createdAt,
      row.updatedAt,
    );
  }

  /**
   * Convert ProductPlan domain entity to database row data.
   * Omits id (generated by DB) and timestamps (handled by DB defaults).
   */
  toData(domain: ProductPlan): typeof productPlans.$inferInsert {
    return {
      productId: domain.productId,
      name: domain.name,
      slug: domain.slug,
      description: domain.description,
      priceBDT: domain.priceBDT.amount,
      priceUSD: domain.priceUSD.amount,
      licenseType: domain.licenseType,
      billingCycle: domain.billingCycle,
      billingDurationMonths: domain.billingDurationMonths,
      maxActivations: domain.maxActivations,
      features: domain.features,
      sortOrder: domain.sortOrder,
      active: domain.active,
    };
  }
}
