/**
 * ProductVersionMapper - Domain-to-data mapper for ProductVersion entity
 *
 * Converts between ProductVersion domain entities and productVersions table rows.
 * Implements IMapper from Phase 14 shared infrastructure (D-23).
 */

import type { IMapper } from "@/shared/infrastructure/repositories";
import { ProductVersion } from "@/modules/products/domain/entities/ProductVersion";
import type { productVersions } from "@/lib/db/schema";

export class ProductVersionMapper implements IMapper<ProductVersion, typeof productVersions.$inferInsert> {
  /**
   * Convert database row to ProductVersion domain entity.
   */
  toDomain(row: typeof productVersions.$inferSelect): ProductVersion {
    return new ProductVersion(
      row.id,
      row.productId,
      row.version,
      row.downloadUrl,
      row.changelog,
      row.status,
      row.releasedAt,
      row.createdAt,
      row.updatedAt,
    );
  }

  /**
   * Convert ProductVersion domain entity to database row data.
   * Omits id (generated by DB) and timestamps (handled by DB defaults).
   */
  toData(domain: ProductVersion): typeof productVersions.$inferInsert {
    return {
      productId: domain.productId,
      version: domain.version,
      downloadUrl: domain.downloadUrl,
      changelog: domain.changelog,
      status: domain.status,
      releasedAt: domain.releasedAt,
    };
  }
}
